# Generated by Django 5.0 on 2025-11-30 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("hubs", "0001_initial"),
        ("investors", "0001_initial"),
        ("vouchers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trade_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("gross_tonnage", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_tonnage", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity_bags", models.IntegerField(blank=True, null=True)),
                (
                    "bag_weight_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=6
                    ),
                ),
                ("buying_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "aflatoxin_qa_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "weighbridge_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "offloading_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "loading_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "transport_cost_per_kg",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "financing_fee_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("financing_days", models.IntegerField(default=0)),
                (
                    "git_insurance_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.30"), max_digits=5
                    ),
                ),
                (
                    "deduction_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "other_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "bennu_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "bennu_fees_payer",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("split", "Split 50/50"),
                        ],
                        default="buyer",
                        max_length=10,
                    ),
                ),
                (
                    "loss_quantity_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "loss_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("loss_reason", models.TextField(blank=True)),
                (
                    "total_trade_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                    ),
                ),
                (
                    "payable_by_buyer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=15,
                    ),
                ),
                (
                    "gross_margin_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=6,
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=6,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("cash_on_delivery", "Cash on Delivery"),
                            ("24_hours", "24 Hours"),
                            ("7_days", "7 Days"),
                            ("14_days", "14 Days"),
                            ("30_days", "30 Days"),
                            ("custom", "Custom Terms"),
                        ],
                        default="24_hours",
                        max_length=30,
                    ),
                ),
                ("payment_terms_days", models.IntegerField(default=1)),
                ("credit_terms_days", models.IntegerField(default=0)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("delivery_location", models.TextField()),
                (
                    "delivery_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("driver_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "driver_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "gross_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tare_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "net_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("ready_for_delivery", "Ready for Delivery"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("allocation_complete", models.BooleanField(default=False)),
                ("requires_voucher_allocation", models.BooleanField(default=False)),
                ("requires_financing", models.BooleanField(default=False)),
                ("financing_complete", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("contract_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="crm.account",
                    ),
                ),
                (
                    "grain_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vouchers.graintype",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hubs.hub"
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quality_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vouchers.qualitygrade",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplied_trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vouchers",
                    models.ManyToManyField(
                        blank=True, related_name="trades", to="vouchers.voucher"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grn_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("point_of_loading", models.CharField(max_length=200)),
                ("loading_date", models.DateField()),
                ("delivery_date", models.DateField()),
                ("delivered_to_name", models.CharField(max_length=200)),
                ("delivered_to_address", models.TextField()),
                ("delivered_to_contact", models.CharField(max_length=50)),
                ("vehicle_number", models.CharField(max_length=50)),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_id_number", models.CharField(max_length=50)),
                ("driver_phone", models.CharField(max_length=20)),
                ("quantity_bags", models.IntegerField(blank=True, null=True)),
                (
                    "gross_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "tare_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("net_weight_kg", models.DecimalField(decimal_places=2, max_digits=12)),
                ("warehouse_manager_name", models.CharField(max_length=100)),
                ("warehouse_manager_signature", models.TextField(blank=True)),
                ("warehouse_manager_date", models.DateField()),
                ("received_by_name", models.CharField(max_length=100)),
                ("received_by_signature", models.TextField(blank=True)),
                ("received_by_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "reason",
                    models.TextField(
                        default="Goods receipt for purchase order into warehouse/stores"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grns",
                        to="trade.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Brokerage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of Trade Value"),
                            ("per_mt", "Per Metric Ton"),
                            ("per_kg", "Per Kilogram"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "commission_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brokerage_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokerages",
                        to="trade.trade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cost_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_per_unit", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_costs",
                        to="trade.trade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeFinancing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "allocation_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "margin_earned",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "investor_margin",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "bennu_margin",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "allocation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_financings",
                        to="investors.investoraccount",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financing_allocations",
                        to="trade.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["-allocation_date"],
            },
        ),
        migrations.CreateModel(
            name="TradeLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("repaid", "Repaid"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "amount_repaid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "interest_earned",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_loans",
                        to="investors.investoraccount",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="trade.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["-disbursement_date"],
            },
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["status", "hub"], name="trade_trade_status_b8e8e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["buyer", "status"], name="trade_trade_buyer_i_e7e9c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["delivery_status"], name="trade_trade_deliver_0f2736_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["created_at"], name="trade_trade_created_e1dfc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["trade_number"], name="trade_trade_trade_n_6cfd1b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tradefinancing",
            unique_together={("trade", "investor_account")},
        ),
    ]
