# Generated by Django 5.0 on 2025-11-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brokerage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tradecost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("pending_allocation", "Pending Allocation"),
                    ("ready_for_delivery", "Ready for Delivery"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
