# Generated by Django 5.0 on 2025-11-30 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_deposited",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total capital deposited",
                        max_digits=15,
                    ),
                ),
                (
                    "total_utilized",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Capital currently in trades/loans",
                        max_digits=15,
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Available for allocation",
                        max_digits=15,
                    ),
                ),
                (
                    "total_margin_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total profits earned",
                        max_digits=15,
                    ),
                ),
                (
                    "total_margin_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Profits withdrawn",
                        max_digits=15,
                    ),
                ),
                (
                    "total_interest_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Interest from loans",
                        max_digits=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestorDeposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "deposit_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investor_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="investors.investoraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-deposit_date"],
            },
        ),
        migrations.CreateModel(
            name="InvestorWithdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "withdrawal_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investor_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="investors.investoraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-withdrawal_date"],
            },
        ),
        migrations.CreateModel(
            name="ProfitSharingAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "profit_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Profit % threshold - below this investor gets 100%",
                        max_digits=5,
                    ),
                ),
                (
                    "investor_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=75.0,
                        help_text="Investor's share % above threshold",
                        max_digits=5,
                    ),
                ),
                (
                    "bennu_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        help_text="bennu's share % above threshold",
                        max_digits=5,
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profit_agreements",
                        to="investors.investoraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
            },
        ),
        migrations.AddIndex(
            model_name="investoraccount",
            index=models.Index(
                fields=["investor"], name="investors_i_investo_8d0d04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investorwithdrawal",
            index=models.Index(
                fields=["investor_account", "status"],
                name="investors_i_investo_e437b3_idx",
            ),
        ),
    ]
