# Generated by Django 5.0 on 2026-02-09 05:13

import django.db.models.deletion
import django.utils.timezone
import sourcing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hubs", "0001_initial"),
        ("vouchers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash Pickup"),
                            ("check", "Bank Check"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=sourcing.models.generate_order_number,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "offered_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price we offer to buy at per kg",
                        max_digits=10,
                    ),
                ),
                (
                    "grain_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="quantity_kg * offered_price_per_kg",
                        max_digits=14,
                    ),
                ),
                (
                    "weighbridge_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "logistics_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "handling_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of all costs — used for margin calculation later",
                        max_digits=14,
                    ),
                ),
                (
                    "logistics_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bennu_truck", "Bennu Truck"),
                            ("supplier_driver", "Supplier Driver"),
                            ("third_party", "Third Party Logistics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("driver_name", models.CharField(blank=True, max_length=255)),
                ("driver_phone", models.CharField(blank=True, max_length=17)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When order was sent to supplier",
                        null=True,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_source_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grain_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vouchers.graintype",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        help_text="Destination hub/warehouse",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hubs.hub",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier's chosen payment method for this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sourcing.paymentpreference",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("driver_name", models.CharField(blank=True, max_length=255)),
                ("vehicle_number", models.CharField(blank=True, max_length=50)),
                (
                    "apparent_condition",
                    models.CharField(
                        choices=[("good", "Good"), ("fair", "Fair"), ("poor", "Poor")],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hubs.hub"
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="sourcing.sourceorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        default=sourcing.models.generate_supplier_invoice_number,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount owed to supplier (= grain_cost from order)",
                        max_digits=14,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "balance_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank/mobile money transaction reference",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Payment"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sourcing.paymentpreference",
                    ),
                ),
                (
                    "source_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_invoice",
                        to="sourcing.sourceorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        default=sourcing.models.generate_payment_number,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("check", "Bank Check"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Bank/mobile money transaction reference — this IS the payment proof",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_supplier_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sourcing.sourceorder",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sourcing.supplierinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("farm_location", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary hub/collection point for this supplier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hubs.hub",
                    ),
                ),
                (
                    "typical_grain_types",
                    models.ManyToManyField(
                        blank=True, related_name="suppliers", to="vouchers.graintype"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="sourcing.supplierprofile",
            ),
        ),
        migrations.AddField(
            model_name="sourceorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_orders",
                to="sourcing.supplierprofile",
            ),
        ),
        migrations.AddField(
            model_name="paymentpreference",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_preferences",
                to="sourcing.supplierprofile",
            ),
        ),
        migrations.CreateModel(
            name="WeighbridgeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weighed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "gross_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "tare_weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="gross - tare. This is the billable/inventory weight.",
                        max_digits=12,
                    ),
                ),
                ("moisture_level", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "quantity_variance_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="net_weight_kg - source_order.quantity_kg (positive = over-delivered)",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weighbridge",
                        to="sourcing.deliveryrecord",
                    ),
                ),
                (
                    "quality_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vouchers.qualitygrade",
                    ),
                ),
                (
                    "source_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weighbridge",
                        to="sourcing.sourceorder",
                    ),
                ),
                (
                    "weighed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weighbridge_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-weighed_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("source_order_created", "New Source Order"),
                            ("source_order_status", "Order Status Update"),
                            ("invoice_generated", "Invoice Generated"),
                            ("payment_made", "Payment Made"),
                            ("payment_proof", "Payment Proof Available"),
                            ("trade_financed", "Your Capital Allocated to Trade"),
                            ("trade_completed", "Trade Completed — Returns Available"),
                            ("capital_returned", "Capital & Margin Returned"),
                            ("delivery_received", "Delivery Received"),
                            ("weighbridge_completed", "Weighbridge Record Created"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="sourcing_no_user_id_327419_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="sourcing_no_user_id_a66f64_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(
                fields=["source_order"], name="sourcing_de_source__dc5cee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrecord",
            index=models.Index(
                fields=["hub", "received_at"], name="sourcing_de_hub_id_fc2a52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["supplier_invoice", "status"],
                name="sourcing_su_supplie_503ba5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["status", "created_at"], name="sourcing_su_status_66b552_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["payment_number"], name="sourcing_su_payment_f696e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierprofile",
            index=models.Index(fields=["user"], name="sourcing_su_user_id_ce6bec_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierprofile",
            index=models.Index(
                fields=["hub", "is_verified"], name="sourcing_su_hub_id_8b19ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(
                fields=["supplier", "status"], name="sourcing_su_supplie_b8066a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(
                fields=["status", "issued_at"], name="sourcing_su_status_1fd766_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(
                fields=["invoice_number"], name="sourcing_su_invoice_b852cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceorder",
            index=models.Index(
                fields=["supplier", "status"], name="sourcing_so_supplie_4ecfef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceorder",
            index=models.Index(
                fields=["hub", "status", "created_at"],
                name="sourcing_so_hub_id_323110_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sourceorder",
            index=models.Index(
                fields=["status", "created_at"], name="sourcing_so_status_81fbe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceorder",
            index=models.Index(
                fields=["order_number"], name="sourcing_so_order_n_cfdfa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentpreference",
            index=models.Index(
                fields=["supplier", "is_default"], name="sourcing_pa_supplie_b205bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weighbridgerecord",
            index=models.Index(
                fields=["source_order"], name="sourcing_we_source__2c3895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weighbridgerecord",
            index=models.Index(
                fields=["weighed_at"], name="sourcing_we_weighed_350efe_idx"
            ),
        ),
    ]
