# Generated by Django 5.0 on 2025-11-30 05:53

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
import vouchers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrainType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="QualityGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("min_moisture", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_moisture", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moisture_level", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "deposit_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("validated", models.BooleanField(default=False)),
                (
                    "grn_number",
                    models.CharField(
                        blank=True,
                        default=vouchers.models.generate_grn_number,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubs.hub"
                    ),
                ),
                (
                    "grain_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vouchers.graintype",
                    ),
                ),
                (
                    "quality_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vouchers.qualitygrade",
                    ),
                ),
            ],
            options={
                "ordering": ["-deposit_date"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Verification"),
                            ("issued", "Issued"),
                            ("transferred", "Transferred"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("pending", "Pending Verification"),
                            ("rejected", "Rejected"),
                        ],
                        default="verified",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("grn_number", models.CharField(blank=True, max_length=50)),
                ("signature_farmer", models.TextField(blank=True)),
                ("signature_agent", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deposit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher",
                        to="vouchers.deposit",
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Redemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "net_payout",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Pickup"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            ("check", "Bank Check"),
                            ("grain", "In-Kind Grain"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="vouchers.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("offer_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("offer_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="vouchers.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-offer_date"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_quantity_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "available_quantity_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "grain_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vouchers.graintype",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubs.hub"
                    ),
                ),
            ],
            options={
                "unique_together": {("hub", "grain_type")},
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("voucher_issue", "Voucher Issue"),
                            ("voucher_transfer", "Voucher Transfer"),
                            ("redemption", "Redemption"),
                            ("purchase", "Purchase"),
                            ("fee", "Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("related_object_id", models.UUIDField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hubs.hub",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="vouchers_le_event_t_dd7360_idx",
                    ),
                    models.Index(
                        fields=["user"], name="vouchers_le_user_id_771a01_idx"
                    ),
                    models.Index(fields=["hub"], name="vouchers_le_hub_id_a2f8cc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateField(default=datetime.date.today)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grain_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vouchers.graintype",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubs.hub",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
                "unique_together": {("hub", "grain_type", "effective_date")},
            },
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(
                fields=["farmer", "deposit_date"], name="vouchers_de_farmer__a7df8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(
                fields=["hub", "deposit_date"], name="vouchers_de_hub_id_96d9a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["holder", "status"], name="vouchers_vo_holder__0f596e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["deposit"], name="vouchers_vo_deposit_79e843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["verification_status"], name="vouchers_vo_verific_fc50c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseoffer",
            unique_together={("investor", "voucher")},
        ),
    ]
