# Generated by Django 5.0 on 2025-11-30 05:53

import django.core.validators
import django.db.models.deletion
import utils.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=utils.helpers.get_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "png", "svg", "jpg", "jpeg", "docx"]
                            )
                        ],
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="utils_docum_content_b4d940_idx",
                    ),
                    models.Index(
                        fields=["content_type"], name="document_content_type_idx"
                    ),
                    models.Index(fields=["object_id"], name="document_object_id_idx"),
                ],
            },
        ),
    ]
