# Generated by Django 5.0 on 2025-11-30 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("crm", "0001_initial"),
        ("hubs", "0001_initial"),
        ("trade", "0001_initial"),
        ("vouchers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="grain_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="vouchers.graintype",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hubs.hub",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="crm.account",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="grn",
            field=models.OneToOneField(
                help_text="One invoice per GRN",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="trade.goodsreceivednote",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="trade",
            field=models.ForeignKey(
                help_text="Trade can have multiple invoices (one per GRN)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="trade.trade",
            ),
        ),
        migrations.AddField(
            model_name="invoicebatch",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_batches",
                to="crm.account",
            ),
        ),
        migrations.AddField(
            model_name="invoicebatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="related_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="accounting.invoice",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="related_trade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trade.trade",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reverses",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="account",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.account",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="accounting.invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reconciled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciled_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="related_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="accounting.payment",
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["period", "hub"], name="accounting__period_834b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["period", "grain_type"], name="accounting__period_dd5d95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="accounting__invoice_f5b9b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["account", "status"], name="accounting__account_903b12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date", "payment_status"],
                name="accounting__due_dat_8bca70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["grn"], name="accounting__grn_id_1d63c8_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["trade"], name="accounting__trade_i_00c917_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["batch_id"], name="accounting__batch_i_b8b5e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicebatch",
            index=models.Index(
                fields=["account", "batch_date"], name="accounting__account_bd0a6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicebatch",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="accounting__period__25cda8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice", "status"], name="accounting__invoice_84fff5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="accounting__payment_710664_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_date", "entry_type"],
                name="accounting__entry_d_4ddb4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["related_trade"], name="accounting__related_b27c13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["related_invoice"], name="accounting__related_bb9726_idx"
            ),
        ),
    ]
