# Generated by Django 5.0 on 2025-11-30 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this hub should be treated as active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="hubs_hub_slug_e7e353_idx"),
                    models.Index(
                        fields=["is_active"], name="hubs_hub_is_acti_9ad54c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HubMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("farmer", "Farmer"),
                            ("agent", "Agent"),
                            ("hub_admin", "Hub Admin"),
                        ],
                        default="farmer",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why user wants to join this hub"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="hubs.hub",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="hubs_hubmem_user_id_46172e_idx"
                    ),
                    models.Index(
                        fields=["hub", "status"], name="hubs_hubmem_hub_id_73aad1_idx"
                    ),
                    models.Index(
                        fields=["status"], name="hubs_hubmem_status_56a410_idx"
                    ),
                ],
                "unique_together": {("user", "hub")},
            },
        ),
    ]
